### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ofou** [v3l0c1r4pt0r/xSDM#23] opened 2017-06-26 22:37 UTC
I got a problem *using* the program. I tried to decrypt the file. What can I do?

```
peel@peel:~/open-source/xSDM$ make
Making all in src
make[1]: Entering directory '/home/peel/open-source/xSDM/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/peel/open-source/xSDM/src'
Making all in tests
make[1]: Entering directory '/home/peel/open-source/xSDM/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/peel/open-source/xSDM/tests'
make[1]: Entering directory '/home/peel/open-source/xSDM'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/peel/open-source/xSDM'
peel@peel:~/open-source/xSDM$ src/xsdm es_windows_7_professional_with_sp1_x64_dvd_u_676947.01.sdc 
 [  OK  ] Opening SDC file
 [ FAIL ]
es_windows_7_professional_with_sp1_x64_dvd_u_676947.01.sdc.key: No such file or directory
peel@peel:~/open-source/xSDM$
``

**Comment by v3l0c1r4pt0r** [comment] 2017-06-27 16:11
Please, read [this tutorial](http://v3l0c1r4pt0r.tk/2014/06/01/how-to-download-from-dreamspark-bypassing-secure-download-manager/). Closing for now. If the problem is really on my side, I will reopen.

**Closed as completed by v3l0c1r4pt0r** 2017-06-27 16:11 UTC

**Comment by sebma** [comment] 2018-01-18 22:46
@v3l0c1r4pt0r 
Hi, the v3l0c1r4pt0r.tk's blog has been turn off : 

> v3l0c1r4pt0r.tk
> 
> This blog has been turned off. I moved to re-ws.pl
> 
> It is likely that what you look for can be found there. If not, there is complete copy of this site on archive.org

Can you give us the new URL for the tutorial on "how to download from dreamspark bypassing secure download manager" ?

Can you also update your README.md URLs pointing to "v3l0c1r4pt0r.tk" with the new URLS ?
